spring.application.name=smartcampus

# Active Profile
spring.profiles.active=dev

logging.level.org.springframework.security=DEBUG

# DevTools logging
spring.devtools.add-properties=true

server:
    error:
        include-message: always
        include-binding-errors: always
        include-stacktrace: on_param