server.port=8080
spring.data.mongodb.uri=mongodb+srv://it23231450_db_user:IT1450@smart-campus-cluster.5gwpwj4.mongodb.net/smartcampus?retryWrites=true&w=majority
spring.data.mongodb.database=smartcampus
spring.security.user.password=admin123

# JWT Configuration
jwt.secret=myverysecuresecretkey_that_is_at_least_32_bytes!
jwt.expiration=86400000

# google oauth
spring.security.oauth2.client.registration.google.client-id=775821170906-n76oam087h1sdk2lij87dk96h3l08odd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=YOUR_REAL_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile
